[2022-05-12 07:56:20,978] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data manual__2022-05-12T07:56:14.631026+00:00 [queued]>
[2022-05-12 07:56:20,986] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data manual__2022-05-12T07:56:14.631026+00:00 [queued]>
[2022-05-12 07:56:20,987] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:56:20,988] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-05-12 07:56:20,989] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:56:20,998] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stop_producer_twitter_data> on 2022-05-12 07:56:14.631026+00:00
[2022-05-12 07:56:21,003] {standard_task_runner.py:52} INFO - Started process 832 to run task
[2022-05-12 07:56:21,005] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stop_live_stream_Dag', 'stop_producer_twitter_data', 'manual__2022-05-12T07:56:14.631026+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/stop_live_stream_dags.py', '--cfg-path', '/tmp/tmpw4zi16m_', '--error-file', '/tmp/tmptxjewa1f']
[2022-05-12 07:56:21,007] {standard_task_runner.py:80} INFO - Job 26: Subtask stop_producer_twitter_data
[2022-05-12 07:56:21,050] {task_command.py:369} INFO - Running <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data manual__2022-05-12T07:56:14.631026+00:00 [running]> on host f74a48c86df7
[2022-05-12 07:56:21,175] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=stop_live_stream_Dag
AIRFLOW_CTX_TASK_ID=stop_producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T07:56:14.631026+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T07:56:14.631026+00:00
[2022-05-12 07:56:21,177] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 07:56:21,178] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'pkill -9 -f /opt/***/dags/producer_tweets.py']
[2022-05-12 07:56:21,185] {subprocess.py:85} INFO - Output:
[2022-05-12 07:56:21,189] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 07:56:21,200] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 07:56:21,203] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=stop_live_stream_Dag, task_id=stop_producer_twitter_data, execution_date=20220512T075614, start_date=20220512T075620, end_date=20220512T075621
[2022-05-12 07:56:21,211] {standard_task_runner.py:97} ERROR - Failed to execute job 26 for task stop_producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 832)
[2022-05-12 07:56:21,259] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 07:56:21,278] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
