[2022-05-12 15:09:20,657] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T15:09:19.587735+00:00 [queued]>
[2022-05-12 15:09:20,667] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T15:09:19.587735+00:00 [queued]>
[2022-05-12 15:09:20,668] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:09:20,669] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 15:09:20,670] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:09:20,679] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): consumer_twitter_data> on 2022-05-12 15:09:19.587735+00:00
[2022-05-12 15:09:20,683] {standard_task_runner.py:52} INFO - Started process 378 to run task
[2022-05-12 15:09:20,688] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'consumer_twitter_data', 'manual__2022-05-12T15:09:19.587735+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmpa_tmhwgz', '--error-file', '/tmp/tmpxe8pgmq0']
[2022-05-12 15:09:20,691] {standard_task_runner.py:80} INFO - Job 91: Subtask consumer_twitter_data
[2022-05-12 15:09:20,745] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T15:09:19.587735+00:00 [running]> on host 29272fb26059
[2022-05-12 15:09:20,926] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=consumer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T15:09:19.587735+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T15:09:19.587735+00:00
[2022-05-12 15:09:20,928] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 15:09:20,929] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/consumer_tweets.py']
[2022-05-12 15:09:20,936] {subprocess.py:85} INFO - Output:
[2022-05-12 15:09:21,877] {subprocess.py:92} INFO - WARNING: An illegal reflective access operation has occurred
[2022-05-12 15:09:21,879] {subprocess.py:92} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-05-12 15:09:21,880] {subprocess.py:92} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-05-12 15:09:21,881] {subprocess.py:92} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-05-12 15:09:21,882] {subprocess.py:92} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-05-12 15:09:21,954] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2022-05-12 15:09:22,019] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2022-05-12 15:09:22,021] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2022-05-12 15:09:22,024] {subprocess.py:92} INFO - org.apache.spark#spark-streaming-kafka-0-10_2.12 added as a dependency
[2022-05-12 15:09:22,026] {subprocess.py:92} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2022-05-12 15:09:22,027] {subprocess.py:92} INFO - org.mongodb.spark#mongo-spark-connector_2.12 added as a dependency
[2022-05-12 15:09:22,029] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-450f2f88-effd-479d-b0a6-0d829b6dacac;1.0
[2022-05-12 15:09:22,030] {subprocess.py:92} INFO - 	confs: [default]
[2022-05-12 15:09:30,357] {subprocess.py:92} INFO - 	found org.apache.spark#spark-streaming-kafka-0-10_2.12;3.1.0 in central
[2022-05-12 15:09:32,189] {subprocess.py:92} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.1.0 in central
[2022-05-12 15:09:34,098] {subprocess.py:92} INFO - 	found org.apache.kafka#kafka-clients;2.6.0 in central
[2022-05-12 15:09:35,866] {subprocess.py:92} INFO - 	found com.github.luben#zstd-jni;1.4.8-1 in central
[2022-05-12 15:09:37,612] {subprocess.py:92} INFO - 	found org.lz4#lz4-java;1.7.1 in central
[2022-05-12 15:09:39,454] {subprocess.py:92} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.2 in central
[2022-05-12 15:09:40,922] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-05-12 15:09:40,929] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 378. PIDs of all processes in the group: [380, 386, 378]
[2022-05-12 15:09:40,932] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 378
[2022-05-12 15:09:40,935] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-12 15:09:40,937] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-05-12 15:09:41,072] {process_utils.py:75} INFO - Process psutil.Process(pid=386, status='terminated', started='15:09:20') (386) terminated with exit code None
[2022-05-12 15:09:41,074] {process_utils.py:75} INFO - Process psutil.Process(pid=378, status='terminated', exitcode=0, started='15:09:20') (378) terminated with exit code 0
[2022-05-12 15:09:41,075] {process_utils.py:75} INFO - Process psutil.Process(pid=380, status='terminated', started='15:09:20') (380) terminated with exit code None
