[2022-05-12 07:40:23,916] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T07:40:23.442797+00:00 [queued]>
[2022-05-12 07:40:23,922] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T07:40:23.442797+00:00 [queued]>
[2022-05-12 07:40:23,923] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:40:23,924] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 07:40:23,925] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:40:23,935] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): consumer_twitter_data> on 2022-05-12 07:40:23.442797+00:00
[2022-05-12 07:40:23,940] {standard_task_runner.py:52} INFO - Started process 778 to run task
[2022-05-12 07:40:23,944] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'consumer_twitter_data', 'manual__2022-05-12T07:40:23.442797+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmpqcx2x9jg', '--error-file', '/tmp/tmp0liyjiar']
[2022-05-12 07:40:23,946] {standard_task_runner.py:80} INFO - Job 7: Subtask consumer_twitter_data
[2022-05-12 07:40:24,003] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T07:40:23.442797+00:00 [running]> on host c5e465c36164
[2022-05-12 07:40:24,049] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=consumer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T07:40:23.442797+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T07:40:23.442797+00:00
[2022-05-12 07:40:24,051] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 07:40:24,053] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/consumer_tweets.py']
[2022-05-12 07:40:24,060] {subprocess.py:85} INFO - Output:
[2022-05-12 07:40:24,101] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-12 07:40:24,102] {subprocess.py:92} INFO -   File "/opt/***/dags/consumer_tweets.py", line 1, in <module>
[2022-05-12 07:40:24,103] {subprocess.py:92} INFO -     from pyspark.sql import SparkSession
[2022-05-12 07:40:24,104] {subprocess.py:92} INFO - ModuleNotFoundError: No module named 'pyspark'
[2022-05-12 07:40:24,105] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 07:40:24,116] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 07:40:24,119] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=live_stream_Dag, task_id=consumer_twitter_data, execution_date=20220512T074023, start_date=20220512T074023, end_date=20220512T074024
[2022-05-12 07:40:24,225] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task consumer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 778)
[2022-05-12 07:40:24,279] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 07:40:24,321] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
